CREATE TABLE IF NOT EXISTS `fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(70) NOT NULL,
  `fantasia` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `cnpj` VARCHAR(45) NULL,
  `insc_estadual` VARCHAR(45) NULL,
  `insc_municipal` VARCHAR(45) NULL,
  `isento` TINYINT NULL,
  `telefone_principal` VARCHAR(20) NULL,
  `telefone_secundario` VARCHAR(20) NULL,
  `contato` VARCHAR(45) NULL,
  `email` VARCHAR(70) NULL,
  `observacao` VARCHAR(255) NULL,
  `end_logradouro` VARCHAR(70) NULL,
  `end_numero` VARCHAR(10) NULL,
  `end_complemento` VARCHAR(45) NULL,
  `end_bairro` VARCHAR(70) NULL,
  `end_cidade` VARCHAR(70) NULL,
  `end_uf` CHAR(2) NULL,
  `end_cep` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB default charset=utf8;